# Generated by Django 4.1.4 on 2023-01-09 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_name_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
